### ISSUE TITLE
Error while running populate.sh script

### ISSUE THREAD

**Issue by okulkarni-eis** [dakrone/elasticsearch-in-action#13]
According to Readme file, I tried to run the populate.sh script on MacOS. Some curl commands ran fine but for some commands, I am getting following error:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"}],"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"},"status":400}`

-----------------------
OS: Mac OS Yosemite
curl 7.43.0
ElasticSearch: 5.2.0

Command executed (from populate.sh):

```
curl -s -XPOST "http://localhost:9200/get-together/event/113?parent=5" -d'{
  "host": "Dave",
  "title": "Elasticsearch at Rangespan and Exonar",
  "description": "Representatives from Rangespan and Exonar will come and discuss how they use Elasticsearch",
  "attendees": ["Dave", "Andrew", "David", "Clint"],
  "date": "2013-06-24T18:30",
  "location_event": {
    "name": "Alumni Theatre",
    "geolocation": "51.51558,-0.117699"
  },
  "reviews": 3
}'
```

**Comment by dakrone** [comment]
@okulkarni-eis are you running `populate.sh` from the 5.x branch of elasticsearch-in-action https://github.com/dakrone/elasticsearch-in-action/tree/5.x ?

**Comment by okulkarni-eis** [comment]
No. I ran it from master. I will try it from 5.X branch now. I was not aware of that branch. Thanks for pointing it out.

**Comment by okulkarni-eis** [comment]
Perfect! It worked like a charm. Could you please update the README.md file to point out that there exists another branch 5.x. By default when we do git checkout, master branch is checked out. Thanks for your help.
