### ISSUE TITLE
"can't specify parent if no parent field has been configured for ES 6.x

### ISSUE THREAD

**Issue by kvelaro** [dakrone/elasticsearch-in-action#15]
It's not indexing in ES 6.x, need help.
Thanks

**Comment by radu-gheorghe** [comment]
Right, this doesn't work for 6.x yet, sorry for that. This PR will eventually address it: https://github.com/dakrone/elasticsearch-in-action/pull/14

Maybe you can try the 5.x branch? It should work, except that you'll need to add the `-H'Content-Type: application/json'` parameter to the curl command (as shown in #14).

**Comment by kvelaro** [comment]
It's not working either, tested already.

**Comment by tlemar** [comment]
I have the same problem on es 6.x

**Comment by kvelaro** [comment]
I suggest you two variants
1. Is to go to the Elasticsearch API page and to look at join datatype
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/parent-join.html
2. Read another book, such as
https://www.google.ru/search?newwindow=1&biw=1920&bih=974&tbm=isch&sa=1&ei=_6ZRW56EJ8SZsgGk8IGQCQ&q=elasticsearch+a+complete+guide&oq=elasticsearch+a+complete+guide&gs_l=img.3..35i39k1j0i24k1l2.3901.4128.0.4316.2.2.0.0.0.0.90.153.2.2.0....0...1c.1.64.img..0.2.150....0.BVIzNyhBNu8#imgrc=PmU7GPre_3IB0M
:

пт, 20 июл. 2018 г., 5:56 tlemar <notifications@github.com>:

**Comment by radu-gheorghe** [comment]
Sorry for the monster delay here. I've just pushed a 6.x branch where there's:
- JSON header
- single type (_doc - should work for 7.x as well)
- join type instead of the older parent-child syntax

This worked for me, but please feel free to reopen or open another issue if you still have trouble.
