### ISSUE TITLE
 [application/x-www-form-urlencoded] is not supported","status":406}

### ISSUE THREAD

**Issue by kingeasternsun** [dakrone/elasticsearch-in-action#16]
[application/x-www-form-urlencoded] is not supported","status":406}

**Comment by techdiverdown** [comment]
have to add -H'Content-Type: application/json' i believe

**Comment by radu-gheorghe** [comment]
Sorry for the very long delay here. I've just committed a 6.x branch that should fix this and subsequent errors. Please let me know if you have other issues.

**Comment by shawn0915** [comment]
same issue, have add `-H "Content-Type: application/json"` into `populate.sh`, like this
```bash
curl -H "Content-Type: application/json" -s -XPOST "$ADDRESS/get-together/group/1" -d'{
```
