### ISSUE TITLE
6.x minor bug

### ISSUE THREAD

**Issue by engimaxp** [dakrone/elasticsearch-in-action#19]
![image](https://user-images.githubusercontent.com/11832788/54329303-18db6100-464c-11e9-8c7e-6224c7adec07.png)
This word should be "aliases",test on 6.6.1.
![image](https://user-images.githubusercontent.com/11832788/54329380-6e177280-464c-11e9-8ca2-8f8c3c564553.png)
there is a missing quotation here,cause the indexing fail.

thx

**Comment by radu-gheorghe** [comment]
Thanks for the catch, @engimaxp! I made the changes just now. I'll close this issue, but feel free to reopen if I missed something.
