### ISSUE TITLE
when using branch 6.x with elasticsearch 7.x, met error 400.

### ISSUE THREAD

**Issue by shawn0915** [dakrone/elasticsearch-in-action#20]
when using branch 6.x with elasticsearch 7.x, met error 400.

elasticsearch version:
```
curl 'localhost:9200'
{
  "name" : "7a7216cec4ae",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "6IW0Nq7qRKSXlh5tfkNI6A",
  "version" : {
    "number" : "7.0.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "b7e28a7",
    "build_date" : "2019-04-05T22:55:32.697037Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.7.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

branch and version:
```git
* 0a6a376 - (origin/6.x) Fixed mapping typo (4 weeks ago) <Radu Gheorghe>
```

the error logs as below:
```log
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."}],"type":"illegal_argument_exception","reason":"The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true."},"status":400}

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse field [relationship_type] of type [text] in document with id '100'"}],"type":"mapper_parsing_exception","reason":"failed to parse field [relationship_type] of type [text] in document with id '100'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 2:24"}},"status":400}
```

**Comment by shawn0915** [comment]
have to add `?include_type_name=true` into `populate.sh` 
like this:https://github.com/shawn0915/elasticsearch-in-action/commit/90c491b05b4ca417c063dd2f630dd5875a0862a7

**Comment by dakrone** [comment]
Yes I think this needs to be updated for the 7.x releases now that ES 7.0.0 has been released.

**Comment by shawn0915** [comment]
thx, ur right. I have adjust my fork and create new branch named 7.x. https://github.com/shawn0915/elasticsearch-in-action/commit/05157e02ec5468ad3acfc15576515d6cdafee914

**Comment by feiyangzhang** [comment]
Dear, is 7.x available ? I am waitting....

**Comment by dakrone** [comment]
Not yet, I'm currently on vacation and unable to update the script. I will update it when I get back.

**Comment by altwei** [comment]
waiting for you

**Comment by amitinfo86** [comment]
Is code available for 7.x version?

**Comment by altwei** [comment]
> Is code available for 7.x version?

unavailable

**Comment by amitinfo86** [comment]
Thank you for information. So for studying this book we need to create script again (populate.sh), because many thing have been removed from latest version of elasticsearch like parent property is removed from latest version.

**Comment by dimboyNew** [comment]
@dakrone 
I think ,we should change request method to **POST** and append **_doc** to url path for 7.x version.plz consider

**Comment by dimboyNew** [comment]
hi :
sorry for mistakes on last comment.
From 7.x version,  mapping type is removed , we should create 2 indices like "group","event" as example in this mapping.json.

Or alternatively, add one filed "eventGroup" as keyword type.

Reference : https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by radu-gheorghe** [comment]
Sorry for the massive delay here. I've just committed a 7.x branch that should work.

I'll close this issue for now, but please feel free to reopen or comment if you have any more issues.

Also, sorry for not seeing your fork @shawn0915

That said, if anyone has a pull requests (or just requests :D ) feel free to open them.
