### ISSUE TITLE
populate.sh gives {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}

### ISSUE THREAD

**Issue by olejardamir** [dakrone/elasticsearch-in-action#22]
$ curl -XGET 'http://localhost:9200'
{
  "name" : "damir-VirtualBox",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "l5HYNXRqS5ScoAkUl3MYnA",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
    "build_date" : "2019-10-28T20:40:44.881551Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

sudo ./populate.sh
-same thing without sudo.
WARNING, this script will delete the 'get-together' and the 'myindex' indices and re-index all data!
Press Control-C to cancel this operation.

Press [Enter] to continue.

Creating 'get-together' index...
{"error":"Incorrect HTTP method for uri [/get-together] and method [POST], allowed: [DELETE, GET, PUT, HEAD]","status":405}
Done creating 'get-together' index.

Indexing data...
Indexing groups...
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done indexing groups.
Indexing events...
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done indexing events.
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [get-together]","resource.type":"index_or_alias","resource.id":"get-together","index_uuid":"_na_","index":"get-together"}],"type":"index_not_found_exception","reason":"no such index [get-together]","resource.type":"index_or_alias","resource.id":"get-together","index_uuid":"_na_","index":"get-together"},"status":404}
Done indexing data.

Creating Templates.
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done Creating Templates.

Adding Dynamic Mapping
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done Adding Dynamic Mapping

Adding Aliases
{"error":"Incorrect HTTP method for uri [/november_2014_invoices] and method [POST], allowed: [DELETE, GET, PUT, HEAD]","status":405}
{"error":"Incorrect HTTP method for uri [/december_2014_invoices] and method [POST], allowed: [DELETE, GET, PUT, HEAD]","status":405}
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done Adding Aliases
Adding Filter Alias
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done Adding Filter Alias

Adding Routing Alias
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
Done Adding Routing Alias

**Comment by radu-gheorghe** [comment]
Hi @olejardamir 

You'll need to switch to a branch that matches your version. I've just added one that should work with your 7.x.

I'll close this issue for now, but feel free to reopen and let me know if you have any issues.
