### ISSUE TITLE
another pattern of join type

### ISSUE THREAD

**Issue by beesman182** [dakrone/elasticsearch-in-action#24]
see below
https://gitee.com/beesman/elasticsearch7x/blob/master/mapping-es7.json
https://gitee.com/beesman/elasticsearch7x/blob/master/populate7.sh
reference:
https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html

**Comment by radu-gheorghe** [comment]
This should be fixed in the 7.x branch. Can you try it?

Either way, it sounds like you found a fix. I'm going to close this issue, but feel free to reopen if I missed anything.

Also, please excuse the late reply :(
