### ISSUE TITLE
populate.sh Not available in version 7.0

### ISSUE THREAD

**Issue by lookingGordo** [dakrone/elasticsearch-in-action#25]
curl -s -H 'content-Type:application/json' -XPOST "$ADDRESS/get-together/event/100?parent=1"

The 7.0 syntax seems to have changed and the declaration with 'parent=1 'will not pass.

**Comment by radu-gheorghe** [comment]
Can you give the 7.x branch a try? https://github.com/dakrone/elasticsearch-in-action/tree/7.x

It should work on 7.x, as it's done around the new [join field](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html).

**Comment by radu-gheorghe** [comment]
I'll close this issue for now, but please let me know if I missed anything (feel free to reopen as well).
