### ISSUE TITLE
Second Edition?

### ISSUE THREAD

**Issue by mousedownmike** [dakrone/elasticsearch-in-action#26]
This book has been an invaluable Elasticsearch reference for me over the years.  The query syntax in 7.x (and probably earlier) has started to diverge a bit from the examples in the book.  If there's any chance of a second edition, I would be first in line to buy it.  I wanted to post this on the Manning Forum but it says it is "410 Gone"... an HTTP code I have not seen that often.

**Comment by radu-gheorghe** [comment]
Hey @mousedownmike! Yeah, unfortunately tech books aren't like wine :( I'm so glad that you'd like to get a 2nd edition, thanks for your kind words! Unfortunately, I don't see that happening soon, or at least not written by me (there was a discussion at some point about others writing a second edition).

As for the forum, it was moved at some point. It's here https://livebook.manning.com/book/elasticsearch-in-action/ if you go on the upper right side there's a "discussion" button, which basically opens the "new" forum.

Aha, but I see the link is from this repo. Let me update it.

**Comment by mousedownmike** [comment]
Thank you, I've made a comment in the new forum.
