### ISSUE TITLE
ability to specify elasticsearch host in populate.sh

### ISSUE THREAD

**Issue by musketyr** [dakrone/elasticsearch-in-action#3]
the `localhost` is fixed there, it should be a variable from the command line argument which defaults to `localhost`

**Comment by musketyr** [comment]
Thanks!

Dne pá 26. 2. 2016 17:34 uživatel Radu Gheorghe <notifications@github.com>
napsal:

**Comment by radu-gheorghe** [comment]
You're welcome! :)
