### ISSUE TITLE
typo in populate.sh

### ISSUE THREAD

**Issue by funderburkjim** [dakrone/elasticsearch-in-action#5]
In running populate.sh,  I noticed an error message for Templates  (UTF8 error).

In the second template (about lines 336-339 of the populate.sh file), there are 
curly double quotes instead of normal  double-quote character  (this in two lines).

WHen these are changed to normal double-quote characters, populate.sh runs without error.
So, I think you should change populate.sh in the repository.

**Comment by dakrone** [comment]
Thanks! I've pushed a commit that fixes this!
