### ISSUE TITLE
Error Indexing events

### ISSUE THREAD

**Issue by sondiek** [dakrone/elasticsearch-in-action#6]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"}],"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"},"status":400}

**Comment by dakrone** [comment]
@sondiek thanks for reporting this, what version of Elasticsearch are you running the script against?

**Comment by sondiek** [comment]
@dakrone I'm using elasticsearch 5.0.1

**Comment by sondiek** [comment]
I submitted a PR #7 that hopefully address the changes to the map and script.
