### ISSUE TITLE
Problem with populate.sh indexing events.

### ISSUE THREAD

**Issue by thebithead** [dakrone/elasticsearch-in-action#9]
I've installed Elastic Search 5 with X-pack.  I modified the ./populate.sh script to workaround the authentication issue.  However, when I run ./populate.sh, I get:

Indexing events...
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"}],"type":"illegal_argument_exception","reason":"Can't specify parent if no parent field has been configured"},"status":400}
...

**Comment by dakrone** [comment]
Related to #7, waiting for that to be merged before re-addressing the authentication issue.

**Comment by thebithead** [comment]
I tried https://github.com/dakrone/elasticsearch-in-action/pull/7 and it has the same indexing events problem.

**Comment by paxtaru** [comment]
It's the "string" type in the events index that's causing issues.  Update mapping.json and replace all "string" with "text" should fix your issue.

**Comment by dakrone** [comment]
Relates to https://github.com/dakrone/elasticsearch-in-action/pull/11

**Comment by dakrone** [comment]
Resolved, see the `5.x` branch
